some better error handling

diff --git a/compiler/Makefile b/compiler/Makefile
--- a/compiler/Makefile
+++ b/compiler/Makefile
@@ -4,15 +4,15 @@ BISON = bison
 CFLAGS = -std=c++20
 INTERPRETER = out/js
 
-.PHONY: run
+.PHONY: run build
 
+build: $(INTERPRETER)
 
-run: $(INTERPRETER)
+run: build
 	$(INTERPRETER) example.js
 
-
-$(INTERPRETER): out/lexer.tab.cpp out/parser.tab.cpp src/interpreter.cpp
-	$(CC) $(CFLAGS) out/lexer.tab.cpp out/parser.tab.cpp src/interpreter.cpp -o $(INTERPRETER)
+$(INTERPRETER): out/lexer.tab.cpp out/parser.tab.cpp src/interpreter.cpp src/error.cpp
+	$(CC) $(CFLAGS) out/lexer.tab.cpp out/parser.tab.cpp src/interpreter.cpp src/error.cpp -o $(INTERPRETER)
 
 out/lexer.tab.cpp: src/lexer.l
 	$(LEX) -o out/lexer.tab.cpp src/lexer.l
@@ -20,11 +20,19 @@ out/lexer.tab.cpp: src/lexer.l
 out/parser.tab.cpp: src/parser.y
 	$(BISON) -Wno-other -d -o out/parser.tab.cpp src/parser.y
 
-test: $(INTERPRETER)
+test: build
 	@echo "Running tests...\n"
-	@for test in tests/**; do \
+	@for test in tests/legit/**; do \
 		echo "Running $$test..."; \
 		$(INTERPRETER) < $$test; \
+		echo " "; \
+	done
+
+test_bad_examples: build
+	@echo "Running bad examples (these should fail with detailed errors)...\n"
+	@for test in tests/bad_examples/**; do \
+		echo "Running $$test..."; \
+		$(INTERPRETER) < $$test || echo "Test failed as expected"; \
 		echo " "; \
 	done
 
